name: E2E Tests

on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        default: false
      specs:
        type: string
        required: false
        default: ""
      debug_specs:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}-e2e
  cancel-in-progress: true

jobs:
  e2e-matrix-builder:
    uses: ./.github/workflows/e2e-matrix-builder.yml
    with:
      chunks: 50
      specs: ${{ inputs.debug_specs && './e2e/test/scenarios/organization/official-collections.cy.spec.js,./e2e/test/scenarios/organization/bookmarks-question.cy.spec.js,./e2e/test/scenarios/filters/filter-bulk.cy.spec.js' || inputs.specs }}
      debug_specs: ${{ inputs.debug_specs }}

  reset-e2e-test-comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Remove test results comment
        uses: actions/github-script@v7
        with:
          script: | # js
            const { owner, repo } = context.repo;

            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: context.issue.number,
            }).catch(console.error);

            if (!comments) {
              return;
            }

            const comment = comments.find((comment) => comment.body.includes('## e2e tests failed on '));

            if (comment) {
              await github.rest.issues.deleteComment({
                owner,
                repo,
                comment_id: comment.id,
              });
            }

  e2e-tests:
    name: ${{ matrix.name }}-${{ matrix.edition }}
    uses: ./.github/workflows/e2e-test.yml
    needs:
      - e2e-matrix-builder
    if: |
      !cancelled() && !inputs.skip
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.e2e-matrix-builder.outputs.matrix) }}
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      edition: ${{ matrix.edition }}
      specs: ${{ matrix.specs }}
      total_chunks: ${{ fromJson(needs.e2e-matrix-builder.outputs.regularChunks) }}
      split_index: ${{ strategy.job-index }}
      tags: ${{ matrix.tags }}
      runner: ${{ matrix.runner }}
      debug_specs: ${{ inputs.debug_specs }}

  # run this separately to make it non-blocking
  flaky-e2e-tests:
    name: Flaky e2e Tests
    uses: ./.github/workflows/e2e-test.yml
    needs:
      - e2e-matrix-builder
    # skip flaky test run if only e2e specs changed as an optimization
    if: |
      !cancelled() && !inputs.skip && needs.e2e-matrix-builder.outputs.isDefaultSpecPattern == 'true'
    secrets: inherit
    with:
      name: Flaky
      tags: "@flaky"

  collect-timings:
    name: Collect E2E Timings
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: e2e-tests
    if: always() && !cancelled()
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            e2e/support
          sparse-checkout-cone-mode: false

      - name: Install cypress-split for merging
        run: |
          echo "Installing cypress-split..."
          npm install cypress-split@^1.24.20
          echo "Verifying installation..."
          npx cypress-split-merge --help || echo "merge command not available"
      
      - name: Download all timing artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: timing-data-*
          path: timing-files
          merge-multiple: false
        continue-on-error: true

      - name: List downloaded files
        run: |
          echo "Downloaded timing files:"
          find timing-files -name "*.json" || echo "No timing files found"
          echo "Directory structure:"
          ls -la timing-files/
          echo "Contents of each artifact folder:"
          for dir in timing-files/*/; do
            echo "=== $dir ==="
            ls -la "$dir"
          done

      - name: Merge split timings
        id: merge
        run: |
          echo "Merging timing files..."
          echo "Looking for files matching pattern: timing-files/**/timings.json"
          find timing-files -name "timings.json" -exec echo "Found: {}" \; -exec head -5 {} \;
          
          npx cypress-split-merge \
            --parent-folder timing-files \
            --split-file timings.json \
            --output e2e/support/timings.json
        env:
          DEBUG: cypress-split
        continue-on-error: true

      - name: Show merged timings
        run: |
          echo "=== Merged Timing Results ==="
          head -50 e2e/support/timings.json 2>/dev/null || echo "No merged timing file found"

      - name: Upload merged timing files
        uses: actions/upload-artifact@v4
        with:
          name: merged-e2e-timings-${{ github.run_id }}
          path: e2e/support/timings.json
          retention-days: 30
        continue-on-error: true

  e2e-tests-result:
    needs:
      - e2e-tests
      - flaky-e2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: e2e-tests-result
    if: always() && !cancelled()
    env:
      E2E_TESTS_RESULT: ${{ needs.e2e-tests.result }}
      FLAKY_E2E_TESTS_RESULT: ${{ needs.flaky-e2e-tests.result }}
    steps:
      - name: Stub
        if: ${{ needs.e2e-tests.result == 'skipped' }}
        run: |
          echo "Didn't run due to conditional filtering"
      - name: Test results
        if: ${{ needs.e2e-tests.result != 'skipped' }}
        run: | # sh
          echo "E2E Tests: ${{ needs.e2e-tests.result }}"
          echo "Flaky E2E Tests: ${{ needs.flaky-e2e-tests.result }}"

          if [ "${{ needs.e2e-tests.result }}" != "success" ]; then
            echo "E2E Tests failed"
            exit 1
          fi
