name: Run tests

on:
  push:
    branches:
      - "master"
      - "release-**"
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
  workflow_dispatch:
    inputs:
      run_e2e_tests:
        description: "Force run e2e tests (ignores file change detection)"
        type: boolean
        default: true
      e2e_only:
        description: "Only run e2e tests (skip backend, frontend, driver tests)"
        type: boolean
        default: true
      reuse_artifacts:
        description: "Reuse existing artifacts instead of building (for testing workflows)"
        type: boolean
        default: false
      oss_artifact_name:
        description: "OSS artifact name to reuse (e.g. metabase-oss-COMMIT_SHA-uberjar)"
        type: string
        default: ""
      ee_artifact_name:
        description: "EE artifact name to reuse (e.g. metabase-ee-COMMIT_SHA-uberjar)"
        type: string
        default: ""
      debug_specs:
        description: "Use minimal specs for debugging (much faster)"
        type: boolean
        default: false

jobs:
  files-changed:
    if: ${{ !contains(github.event.pull_request.labels.*.name,'ci skip') }}
    name: Check which files changed
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      e2e_all: ${{ steps.changes.outputs.e2e_all }}
      e2e_all_files: ${{ steps.changes.outputs.e2e_all_files }}
      e2e_specs: ${{ steps.changes.outputs.e2e_specs }}
      e2e_specs_files: ${{ steps.changes.outputs.e2e_specs_files }}
      backend_all: ${{ steps.changes.outputs.backend_all }}
      frontend_all: ${{ steps.changes.outputs.frontend_all }}
      frontend_sources: ${{ steps.changes.outputs.frontend_sources }}
      documentation: ${{ steps.changes.outputs.documentation }}
    steps:
      - uses: actions/checkout@v4
      - name: Test which files changed
        uses: dorny/paths-filter@v3.0.0
        id: changes
        with:
          token: ${{ github.token }}
          # comma separated list of files
          list-files: csv
          filters: .github/file-paths.yaml

  static-viz-files-changed:
    name: Check whether static-viz files changed
    if: ${{ !contains(github.event.pull_request.labels.*.name,'ci skip') }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      static_viz: ${{ steps.static_viz.outputs.static_viz }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
        with:
          m2-cache-key: "files-changed"
      - name: Build static-viz frontend
        run: yarn build-static-viz
        env:
          MB_EDITION: ee
      - name: Upload Static Viz Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-viz-bundle-${{ github.sha }}
          path: resources/frontend_client/app/dist

      - name: Check for static viz changes
        uses: dorny/paths-filter@v3.0.0
        id: static_viz
        with:
          token: ${{ github.token }}
          filters: .github/static-viz-sources.yaml

  uberjar:
    needs: [files-changed, static-viz-files-changed]
    if: ${{ !cancelled() && !inputs.reuse_artifacts && !(needs.files-changed.outputs.documentation == 'true' && needs.files-changed.outputs.backend_all == 'false' && needs.files-changed.outputs.frontend_all == 'false' && needs.files-changed.outputs.e2e_all == 'false') }}
    uses: ./.github/workflows/uberjar.yml
    secrets: inherit

  download-artifacts:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: ${{ inputs.reuse_artifacts && inputs.oss_artifact_name != '' && inputs.ee_artifact_name != '' }}
    steps:
      - name: Download artifacts using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Downloading OSS artifact: ${{ inputs.oss_artifact_name }}"
          gh api repos/${{ github.repository }}/actions/artifacts \
            --jq '.artifacts[] | select(.name=="${{ inputs.oss_artifact_name }}") | .archive_download_url' \
            | head -1 \
            | xargs -I {} curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" {} -o oss-artifact.zip
          
          echo "Downloading EE artifact: ${{ inputs.ee_artifact_name }}"
          gh api repos/${{ github.repository }}/actions/artifacts \
            --jq '.artifacts[] | select(.name=="${{ inputs.ee_artifact_name }}") | .archive_download_url' \
            | head -1 \
            | xargs -I {} curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" {} -o ee-artifact.zip
            
          echo "Extracting artifacts..."
          mkdir -p oss-extract ee-extract
          
          echo "Extracting OSS artifact..."
          unzip -q oss-artifact.zip -d oss-extract/
          
          echo "Extracting EE artifact..."
          unzip -q ee-artifact.zip -d ee-extract/
          
          echo "Preparing artifacts with correct directory structure..."
          # Keep the full directory structure that the e2e runner expects
          
          echo "Found files in OSS extract:"
          ls -la oss-extract/target/uberjar/
          echo "Found files in EE extract:"
          ls -la ee-extract/target/uberjar/
          
      - name: Re-upload OSS as expected name
        uses: actions/upload-artifact@v4
        with:
          name: metabase-oss-${{ github.sha }}-uberjar
          path: oss-extract/
          
      - name: Re-upload EE as expected name
        uses: actions/upload-artifact@v4  
        with:
          name: metabase-ee-${{ github.sha }}-uberjar
          path: ee-extract/

  backend-tests:
    if: ${{ !cancelled() && !inputs.e2e_only }}
    needs: [files-changed, static-viz-files-changed]
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.backend_all != 'true' && needs.static-viz-files-changed.outputs.static_viz != 'true' }}

  semantic-search-tests:
    needs: files-changed
    uses: ./.github/workflows/semantic-search.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.backend_all != 'true' }}

  app-db-tests:
    if: ${{ !inputs.e2e_only }}
    needs: files-changed
    uses: ./.github/workflows/app-db.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.backend_all != 'true' }}

  driver-tests:
    if: ${{ !inputs.e2e_only }}
    needs: files-changed
    uses: ./.github/workflows/drivers.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.backend_all != 'true' }}

  frontend-tests:
    if: ${{ !inputs.e2e_only }}
    needs: files-changed
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.frontend_all != 'true' }}
      skip-lint: ${{ needs.files-changed.outputs.frontend_all != 'true' && needs.files-changed.outputs.e2e_specs != 'true' }}

  e2e-tests:
    needs: [files-changed, uberjar, download-artifacts]
    if: always() && !cancelled() && (needs.uberjar.result == 'success' || needs.download-artifacts.result == 'success' || needs.uberjar.result == 'skipped')
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.e2e_all != 'true' && !inputs.run_e2e_tests }}
      # Use debug specs if debugging, otherwise use normal spec logic
      specs: ${{ inputs.debug_specs && 'e2e/test/scenarios/onboarding/*.cy.spec.*' || (needs.files-changed.outputs.e2e_all_files == needs.files-changed.outputs.e2e_specs_files && needs.files-changed.outputs.e2e_specs_files || '') }}

  sdk-tests:
    needs: files-changed
    uses: ./.github/workflows/embedding-sdk.yml
    secrets: inherit

  pr-env:
    needs: [uberjar]
    if: |
      !cancelled() &&
      contains(github.event.pull_request.labels.*.name, 'PR-Env')
    uses: ./.github/workflows/pr-env.yml
    secrets: inherit

  containerize:
    needs: [uberjar]
    if: |
      !cancelled() &&
      needs.uberjar.result == 'success' &&
      (
        (github.event_name == 'push' && contains(fromJson('["master", "metabot-v3-main", "internal-tools"]'), github.ref_name)) ||
        (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build-docker-uberjar'))
      )
    uses: ./.github/workflows/containerize-uberjar.yml
    secrets: inherit
