name: Test Cypress Split
on:
  workflow_dispatch:
    inputs:
      chunks:
        description: 'Number of parallel chunks'
        type: number
        required: false
        default: 3
      debug:
        description: 'Enable DEBUG output'
        type: boolean
        required: false
        default: true

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Create container matrix
        id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: ${{ inputs.chunks }}

      - name: Print matrix
        run: echo '${{ steps.prepare.outputs.matrix }}'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false

  test-split:
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test timing file
        run: |
          mkdir -p test-cypress-split
          cat > test-cypress-split/timings.json << 'EOF'
          {
            "durations": [
              {"spec": "test-cypress-split/cypress/e2e/test1.cy.js", "duration": 2000},
              {"spec": "test-cypress-split/cypress/e2e/test2.cy.js", "duration": 3000},
              {"spec": "test-cypress-split/cypress/e2e/test3.cy.js", "duration": 1500},
              {"spec": "test-cypress-split/cypress/e2e/test4.cy.js", "duration": 4000},
              {"spec": "test-cypress-split/cypress/e2e/test5.cy.js", "duration": 2500},
              {"spec": "test-cypress-split/cypress/e2e/test6.cy.js", "duration": 1800}
            ]
          }
          EOF

      - name: Create test specs
        run: |
          mkdir -p test-cypress-split/cypress/e2e
          
          # Create 6 simple test files
          for i in {1..6}; do
            cat > test-cypress-split/cypress/e2e/test${i}.cy.js << EOF
          describe('Test ${i}', () => {
            it('should pass test ${i}', () => {
              cy.wrap(null).then(() => {
                cy.wait($((i * 500))); // Different wait times to simulate different durations
                expect(true).to.be.true;
              });
            });
          });
          EOF
          done

      - name: Create cypress config
        run: |
          cat > test-cypress-split/cypress.config.js << 'EOF'
          const { defineConfig } = require('cypress');
          const cypressSplit = require('cypress-split');

          module.exports = defineConfig({
            e2e: {
              baseUrl: 'https://example.com',
              setupNodeEvents(on, config) {
                cypressSplit(on, config);
                return config;
              },
              specPattern: 'cypress/e2e/**/*.cy.js',
              supportFile: false,
            },
          });
          EOF

      - name: Debug environment
        run: |
          echo "=== Environment Variables ==="
          echo "SPLIT: ${{ strategy.job-total }}"
          echo "SPLIT_INDEX: ${{ strategy.job-index }}"
          echo "Working directory: $(pwd)"
          ls -la test-cypress-split/

      - name: Run cypress with split
        uses: cypress-io/github-action@v6
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          SPLIT_FILE: 'timings.json'
          DEBUG: ${{ inputs.debug && 'cypress-split' || '' }}
        with:
          working-directory: test-cypress-split
          install-command: npm install cypress cypress-split
          runTests: true
          browser: electron

      - name: Check results
        run: |
          echo "=== After Test Execution ==="
          echo "Working directory: $(pwd)"
          echo "Files in test directory:"
          ls -la test-cypress-split/
          echo "Looking for timing files:"
          find test-cypress-split -name "*.json" -type f
          echo "Content of timings.json if it exists:"
          cat test-cypress-split/timings.json 2>/dev/null || echo "timings.json not found"

      - name: Upload timing data
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-split-results-${{ strategy.job-index }}
          path: |
            test-cypress-split/timings.json
            test-cypress-split/cypress/screenshots
            test-cypress-split/cypress/videos
          if-no-files-found: ignore

  merge-timings:
    needs: test-split
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: split-results
          
      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -R split-results/

      - name: Merge timing files
        id: merge
        run: |
          echo "Attempting to merge timing files..."
          npx cypress-split-merge \
            --parent-folder split-results \
            --split-file timings.json \
            --output timings.json \
            --set-gha-output merged-timings
        env:
          DEBUG: cypress-split

      - name: Show merged results
        run: |
          echo "=== Merged Timing Results ==="
          cat timings.json 2>/dev/null || echo "No merged timing file found"
          echo "GHA output: ${{ steps.merge.outputs.merged-timings }}"

      - name: Upload merged timings
        uses: actions/upload-artifact@v4
        with:
          name: merged-timings
          path: timings.json