name: Update E2E Timings

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: "Number of days to look back for timing artifacts"
        type: number
        default: 7
  push:
    branches:
      - master
      - generate-new-test-timings
    paths:
      - ".github/workflows/update-e2e-timings.yml"
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: "0 6 * * 0"

jobs:
  collect-and-average-timings:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Collect and average timing data
        uses: actions/github-script@v7
        with:
          script: |
            const { collectAndAverageTimings } = require('${{ github.workspace }}/.github/scripts/average-e2e-timings.js');
            await collectAndAverageTimings({
              github,
              context,
              token: '${{ secrets.GITHUB_TOKEN }}',
              branch: 'generate-new-test-timings',
              daysBack: ${{ inputs.days_back || 7 }},
              existingTimingsPath: 'e2e/support/timings.json'
            });

      - name: Set up git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="update-e2e-timings-$(date +%Y%m%d-%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch name will be: $BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: generate-new-test-timings
          commit-message: |
            Update E2E test timings with averaged data

            Collected timing data from ${{ inputs.days_back || 7 }} days of test runs.
            All specs with timing data were included (simple averages).

            🤖 Generated automatically by update-e2e-timings workflow

            Co-Authored-By: GitHub Actions <actions@github.com>
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "[chore] Update E2E test timings with recent data"
          body: |
            ## Summary
            This PR updates the E2E test timing data with averaged values from recent test runs.

            ## Details
            - 📅 Collected data from the last **${{ inputs.days_back || 7 }} days** of test runs

            ## Generated automatically
            🤖 This PR was created automatically by the `update-e2e-timings` workflow.
            The timing data helps cypress-split optimize test distribution across parallel jobs.

            Co-Authored-By: GitHub Actions <actions@github.com>
          add-paths: e2e/support/timings.json
